package com.codingshuttle.projects.lovable_clone.entity;

import com.codingshuttle.projects.lovable_clone.enums.MessageRole;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.FieldDefaults;

import java.time.Instant;

/*
 * Entity Usage:
 * Represents a single bubble in a chat conversation. It stores the actual text content,
 * identifies who spoke (User vs AI), and logs any "Tools" (functions) the AI tried to run
 * to solve the user's request.
 */
@Getter
@Setter
@FieldDefaults(level = AccessLevel.PRIVATE)
public class ChatMessage {

    Long id; // PK: Unique identifier for this specific message

    ChatSession chatSession; // FK: The conversation thread this message belongs to

    String content; // Payload: The actual text message sent by the user or generated by the AI

    MessageRole role; // Context: Identifies the sender (USER, ASSISTANT, SYSTEM) to structure the dialogue

    String toolCalls; // Action: JSON string recording any specific functions the AI invoked (e.g., "create_file")

    Integer tokensUsed; // Cost: The specific computational cost (token count) for this single message bubble

    Instant createdAt; // Audit: Exact time the message was sent or generated
}